### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by ajhenley** [awijeet/Image_cropping_in_rails4#1]
This example has been really helpful.

Quick Question.

How would I modify this to allow updated listings with images (if there) to use the cropper as well?

**Comment by awijeet** [comment]
Do you mean multiple cropper on single page.

**Comment by ajhenley** [comment]
no, i mean this only works for creating a new entry. when you update an existing entry and upload a new photo, it doesnt let you crop the new image. it does it automatically.

**Comment by awijeet** [comment]
you can add a test inside update controller to check if user puts new image, and then call 
 render "cropper"

**Comment by ajhenley** [comment]
Ok, thanks.

Now that I look at it, it takes me to the cropper page and back but it is ignoring the cropping box and just cropping it to the default. It looks like my cropper.rb is never being used. Does it need to be registered somewhere or something?

**Comment by awijeet** [comment]
I have given you the way, i would love if you dig into it more, and find the solution by own. I wish i could help you more, but i am really busy with project. 

If you want me to fix it as such, please contact me at awijeet@rubyonrails4ror.com

**Comment by awijeet** [comment]
I am closing it, as I haven't got any response
